name: 'Setup'
description: 'Setup pnpm, repo and cache'
runs:
  using: "composite"
  steps:
    # https://github.com/pnpm/pnpm/issues/9191
    - name: Set up pnpm global bin directory`
      run: |
        if [ "$RUNNER_OS" == "Windows" ]; then
          PNPM_HOME=/c/Program\ Files/Git/home/runner/.local/share/pnpm
        elif [ "$RUNNER_OS" == "Linux" ]; then
          PNPM_HOME=/home/runner/.local/share/pnpm
        fi
        echo "PNPM_HOME=$PNPM_HOME" >> "$GITHUB_ENV"
        echo "$PNPM_HOME" >> "$GITHUB_PATH"
      shell: bash
    - name: Enable corepack
      run: |
        npm install -g corepack@latest
        corepack enable
      shell: bash
    - name: Cache
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: 'pnpm'
        cache-dependency-path: |
          pnpm-lock.yaml
          netlify/functions/ksc-results/pnpm-lock.yaml
    - name: Install
      run: |
        pnpm install
      shell: bash
