[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.settings]
    preset = "desktop"

  [[plugins.inputs.audits]]
    path = "/krm-ui/"

[dev]
  command = "pnpm start" # Command to start your dev server
  targetPort = 5173 # The port for your application server, framework, or site generator
  port = 5174 # The port that the Netlify Dev will be accessible on
  publish = "." # If you use a _redirect file, provide the path to your static content folder
  noOpen = true

[[redirects]]
  from ="/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/krm-ui/@vite*"
  to = "@vite/:splat"

[[redirects]]
  from = "/krm-ui/src*"
  to = "/src/:splat"

[[redirects]]
  from = "/krm-ui/*"
  to = "/krm-ui/"
  status = 200

[[redirects]]
  from = "/*"
  to = "/krm-ui"
  status = 302
