name: Test and Deploy

permissions:
  contents: read

on:
  push:
    branches: ["main"]

  # Allows manual executions
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "build"
  cancel-in-progress: false

jobs:
  smoke:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Setup
      uses: ./.github/actions/setup
    - name: Install Playwright Browsers
      run: pnpm exec playwright install chromium --with-deps --only-shell
    - name: Run Playwright tests
      run: pnpm e2e --grep "Realistic"
    - uses: actions/upload-artifact@v6
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - name: Test
        run: pnpm test
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - name: Check TS violations
        run: pnpm check
      - name: Check ESLint violations
        run: pnpm lint
  deploy:
    needs: [test, check, smoke]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup
        uses: ./.github/actions/setup
      - name: Update version
        run: .github/update_version.sh
      - name: Install netlify
        run: pnpm install -g netlify-cli
      - name: Download Playwright report
        uses: actions/download-artifact@v8
        with:
          name: playwright-report
          path: dist/krm-ui-playwright
      - name: Build and deploy to Netlify
        env:
          NODE_ENV: production
          VITE_CLERK_PUBLISHABLE_KEY: "${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }}"
          NETLIFY_SITE_ID: "${{ secrets.NETLIFY_SITE_ID }}"
          NETLIFY_AUTH_TOKEN: "${{ secrets.NETLIFY_API_TOKEN }}"
        run: .github/deploy.sh
