name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          awk '
            /^## / {
              release+=1;
              if (release > 1) {
                exit;
              }
            }
            !/<!--/ {
              if (release > 0) {
                print
              }
            }' CHANGELOG.md > THIS_CHANGELOG.md
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag}" \
              --notes-file=THIS_CHANGELOG.md
